M48
; DRILL file {KiCad 7.0.8} date Sun Nov 12 21:10:43 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-12T21:10:43-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.200
%
G90
G05
T1
X94.79Y-107.085
X94.79Y-112.865
T2
X159.475Y-79.975
X171.475Y-79.975
X174.725Y-111.775
X183.475Y-79.975
X195.475Y-79.975
T0
M30
